on: [push]

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-16.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
          architecture: x64

      - run: mvn clean install -DskipTests=true

      - run: mvn test

  deploy:
    name: "Deployment to K8s"
    runs-on: ubuntu-16.04
    timeout-minutes: 10
    needs: build
    steps:
      #- uses: actions/download-artifact@master
      #  with:
      #    name: project
      #    path: ./

#      - name: "GCP Authenticate"
#        uses: actions/gcloud/auth@master
#        env:
#          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
#        with:
#          run: "container clusters list"

      - name: "Build the image"
        #uses: actions/docker/cli@master
        #with:
        #  run: build -t eu.gcr.io/gara-quant/bollinger-bands .
        run: build -t eu.gcr.io/your-project/gpc-ci .

      - name: "Tagging ${GITHUB_SHA}"
#        uses: actions/docker/cli@master
#        with:
#          run: tag eu.gcr.io/gara-quant/bollinger-bands:latest eu.gcr.io/gara-quant/bollinger-bands:${GITHUB_SHA}
        run: tag eu.gcr.io/your-project/gpc-ci:latest eu.gcr.io/your-project/gpc-ci:${GITHUB_SHA}

#      - name: "Pushing...."
#        uses: actions/docker/cli@master
#        with:
#          run: push eu.gcr.io/gara-quant/bollinger-bands:${GITHUB_SHA}
