on: [push]

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-16.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          architecture: x64

      - run: mvn clean install

      - run: curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
      - run: chmod +x codacy-coverage-reporter
      - run: ./codacy-coverage-reporter report -l Java -r ./target/site/jacoco/jacoco.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}


      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
