on: [push]

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-16.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
          architecture: x64

      # - run: mvn clean install -DskipTests=true
      - run: mvn clean install

      - name: Godacov Report
        uses: brpaz/godacov-action@v1.0.3
        with:
          reportPath: 'target/site/jacoco'
          codacyToken: ${{ secrets.CODACY_TOKEN }}
          commitId: ${{ github.sha }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
